TRUNCATE TABLE 
    LOG, TAMSANG_CONFIG, COST, PAYMENT, MEMBER, MEMBER_TYPE, 
    ORDER_ITEM_TOPPING, ORDER_ITEM, ORDERS, TABLES, 
    MENU_TOPPING, MENU_INGREDIENT, INGREDIENT, CATEGORY_INGREDIENT, 
    MENU, CATEGORY_MENU 
RESTART IDENTITY CASCADE;